services:
  - type: web
    name: cardgenerator
    env: java
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar build/libs/CardGeneratorVictorNicolauNeto-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/./urandom
      - key: PORT
        generateValue: true
      - key: SPRING_PROFILES_ACTIVE
        value: prod